#!/bin/bash

cd "$(dirname "$0")"

if [ ! -d "venv" ]; then
    python3 -m venv venv
fi

source venv/bin/activate
pip install -q --disable-pip-version-check -r requirements.txt
python src/game_of_life.py

deactivate
